<Project Sdk="Microsoft.NET.Sdk">

	<!-- Import tModLoader mod properties -->
	<Import Project="..\tModLoader.targets" />

	<!-- General -->
	<PropertyGroup>
		
	</PropertyGroup>
	<ItemGroup>
	  <None Remove="Effects\WeaponSkinShader.fx" />
	</ItemGroup>
	<ItemGroup>
	  <Folder Include="Systems\WeaponSystem\WeaponParts\Gun\Scope\" />
	</ItemGroup>

	<!-- References -->

</Project>